apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: eticket
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: shashidas/eticket-backend:v2.0
          ports:
            - containerPort: 7001
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: eticket
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 7001
      targetPort: 7001
      protocol: TCP
      nodePort: 31100
