apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: eticket
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ''
  resources:
    requests:
      storage: 5Gi
